### ISSUE TITLE
V2 can you call meteor message format mf in the server 

### ISSUE THREAD

**Issue by almogdesign** [gadicc/meteor-messageformat#139]
I'm calling mf('block', 'Block') in the server on cursor collection for each but I keep getting the following error 

 at app/server/check_expired_dates.js:16:25
    at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:965:1)
    at [object Object].Cursor.(anonymous function) (packages/mongo/mongo_driver.js:812:1)
    at [object Object].cursorProto.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/db.js:127:1)
    at [object Object].kadira_Cursor_forEach [as forEach] (packages/meteorhacks:kadira/lib/hijack/set_labels.js:63:1)
    at [object Object].Meteor.methods.checkBlocksFieldStatusTo (app/server/check_expired_dates.js:7:36)
    at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:161:1)
    at packages/check/match.js:109:1

**Comment by gadicc** [comment]
Same here... you showed where the error occurred but left out the actual error.

But yes, `mf()` can be used on the server (either inside of a method/publish block or by manually specifying the locale to generate stuff server side).

**Comment by almogdesign** [comment]
Sorry found a workaround forgot to close
