### ISSUE TITLE
V2 mf not working in collections(lib)

### ISSUE THREAD

**Issue by almogdesign** [gadicc/meteor-messageformat#140]
I'm doing the following in my collection but I keep getting the following error 

var message = mf('block', 'Block') + ' ' + productionUnitCode + ', ' +  mf('forProducer', 'For producer') + ' ' +  producerName + ' ' + mf('organicFieldStatusToHasExpired', 'organic field status to has expired');

 at mf (packages/msgfmt:core/lib/mfPkg/messageformat.js:106:1)
    at createExpiredNotification (app/lib/collections/notifications.js:43:19)
    at app/server/check_expired_dates.js:9:13
    at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:965:1)
    at [object Object].Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:812:1)
    at [object Object].Meteor.methods.checkBlocksFieldStatusTo (app/server/check_expired_dates.js:6:36)
    at packages/check/match.js:109:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1614:1)

**Comment by gadicc** [comment]
Hey, it seems you pasted everything but the actual error :)  Can you copy that in too?

Also, are you separating all your strings like that because you're reusing those small parts?  I guess it's ok since I think you're only using two languages... but some languages have weird rules regarding word placement, one of the reasons why messageformat has such a big advantage over gettext.

**Comment by almogdesign** [comment]
Yes, I was calling it from the server found a workaround but forgot to close
