### ISSUE TITLE
[v2] Errors when starting server

### ISSUE THREAD

**Issue by tcastelli** [gadicc/meteor-messageformat#148]
I thought i got this error just because i removed some strings from the database manually last time, but lately I'm getting it again whenever i have a large number of new translated strings and upload the new mfAll.js.
The extac error is this one

    MongoError: '$set' is empty. You must specify a field like so: {$set: {<field>: ...}}

    [1]: at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:398:15)

    [2]: at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)

    [3]: at [object Object].MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:678:1)

    [4]: at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:575:1)

    [5]: at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed:collection2/collection2.js:165:1)

    [6]: at Object.mfPkg.langUpdate (packages/msgfmt:core/lib/mfPkg/messageformat-server.js:126:1)

    [7]: at Object.mfPkg.syncAll (packages/msgfmt:core/lib/mfPkg/messageformat-server.js:167:1)

    [8]: at app/server/mfAll.js:1:42

    [9]: at app/server/mfAll.js:19035:3

    [10]: at /bundle/bundle/programs/server/boot.js:222:10

    [11]: - - - - -

    [12]: at Object.toError (/bundle/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)

    [13]: at /bundle/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/collection/core.js:577:27

    [14]: at /bundle/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/db.js:1195:7

    [15]: at /bundle/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/db.js:1903:9

    [16]: at Server.Base._callHandler (/bundle/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)

    [17]: at /bundle/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:487:18

    [18]: at [object Object].MongoReply.parseBody (/bundle/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)

    [19]: at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)

    [20]: at [object Object].emit (events.js:95:17)

    [21]: at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)

It normally gets solved by restarting the server a few times. It's like it tries to add the values from syncall but the first time misses (or takes too much time) and then on the second chances the previous work from sync is kept and it can be completed. Quite strange, did nothing special besides adding new translations. (when i update the file with 2 or 3 new strings this never happens)

**Comment by DSpeichert** [comment]
Hi @tcastelli,
I should have suppressed the fatal error in the referenced commit.
You can try the updated code straight from git (check it out into packages/) or simply wait for @gadicc to release another version to atmosphere.

This might require more thorough review to make sure we aren't masking any other errors.

**Comment by tcastelli** [comment]
Thanks!, I prefer to wait until @gadicc updates the atmosphere package, I'll survive for now :)
