### ISSUE TITLE
error which is very hard to diagnose

### ISSUE THREAD

**Issue by Maxhodges** [gadicc/meteor-messageformat#159]
Is there a debugging mode for messageFormat? I got an error which is very hard to debug. I've been putting mf helpers in many pages of my site. Not sure what I did wrong, but now I can't compile my app anymore. Guess I have to revert to an earlier commit and start over :( Is there anyway to get more specific errors regarding this problem?

```
W20150825-23:01:38.091(9)? (STDERR) 
W20150825-23:01:38.091(9)? (STDERR) /Users/maxhodges/.meteor/packages/meteor-tool/.1.1.4.z224am++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150825-23:01:38.092(9)? (STDERR) 						throw(ex);
W20150825-23:01:38.092(9)? (STDERR) 						      ^
W20150825-23:01:38.093(9)? (STDERR) Error: A method named '/mfStrings/insert' is already defined
W20150825-23:01:38.093(9)? (STDERR)   at /Users/maxhodges/Documents/github/wreClient/.meteor/local/build/programs/server/packages/ddp.js:2289:15
W20150825-23:01:38.093(9)? (STDERR)   at Function._.each._.forEach (/Users/maxhodges/Documents/github/wreClient/.meteor/local/build/programs/server/packages/underscore.js:147:22)
W20150825-23:01:38.093(9)? (STDERR)   at [object Object]._.extend.methods (/Users/maxhodges/Documents/github/wreClient/.meteor/local/build/programs/server/packages/ddp.js:2287:7)
W20150825-23:01:38.093(9)? (STDERR)   at [object Object].Mongo.Collection._defineMutationMethods (/Users/maxhodges/Documents/github/wreClient/.meteor/local/build/programs/server/packages/mongo.js:4251:24)
W20150825-23:01:38.093(9)? (STDERR)   at new Mongo.Collection (/Users/maxhodges/Documents/github/wreClient/.meteor/local/build/programs/server/packages/mongo.js:3556:8)
W20150825-23:01:38.093(9)? (STDERR)   at [object Object].ns.Collection (/Users/maxhodges/Documents/github/wreClient/.meteor/local/build/programs/server/packages/lai_collection-extensions.js:93:27)
W20150825-23:01:38.093(9)? (STDERR)   at [object Object].ns.Collection (/Users/maxhodges/Documents/github/wreClient/.meteor/local/build/programs/server/packages/matb33_collection-hooks.js:214:27)
W20150825-23:01:38.093(9)? (STDERR)   at /Users/maxhodges/Documents/github/wreClient/.meteor/local/build/programs/server/packages/msgfmt_core.js:2926:16
W20150825-23:01:38.093(9)? (STDERR)   at /Users/maxhodges/Documents/github/wreClient/.meteor/local/build/programs/server/packages/msgfmt_core.js:3074:4
W20150825-23:01:38.093(9)? (STDERR)   at /Users/maxhodges/Documents/github/wreClient/.meteor/local/build/programs/server/packages/msgfmt_core.js:3485:3
W20150825-23:01:38.093(9)? (STDERR)   at /Users/maxhodges/Documents/github/wreClient/.meteor/local/build/programs/server/boot.js:222:10
W20150825-23:01:38.093(9)? (STDERR)   at Array.forEach (native)
W20150825-23:01:38.093(9)? (STDERR)   at Function._.each._.forEach (/Users/maxhodges/.meteor/packages/meteor-tool/.1.1.4.z224am++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150825-23:01:38.094(9)? (STDERR)   at /Users/maxhodges/Documents/github/wreClient/.meteor/local/build/programs/server/boot.js:117:5

```

**Comment by Maxhodges** [comment]
it's cool. nevermind! had a package conflict.
