### ISSUE TITLE
production version?

### ISSUE THREAD

**Issue by Maxhodges** [gadicc/meteor-messageformat#248]
Hi I started getting this error today

```
Exception in callback of async function: TypeError: handlers[path.extname(...).substr(...)] is not a function
I20161216-11:38:48.775(9)?     at packages/msgfmt_extract.js:124:45
I20161216-11:38:48.776(9)?     at runWithEnvironment (packages/meteor.js:1176:24)
```

We've been running these versions:
```
msgfmt:core@2.0.0-preview.12
msgfmt:extract@2.0.0-preview.9
msgfmt:ui-dev-only
```

Not sure what version I should be running. Might another version make my program go away?

**Comment by gadicc** [comment]
Hey Max

This is another surprising one :)  Files are only handled if they match [`/\.(html|js|coffee|jsx|jade)$/)`](https://github.com/gadicc/meteor-messageformat/blob/v2/packages/extract/extract.js#L54) and then `handler.html` etc are all defined in the same file.

Is it possible that `String.prototype.substr` has been overwritten and is returning non-standard values?  As best I can tell from the error, all the chained functions in the square braces are running, but for some reason it's not returning one of the defined extensions above.  The other options is that the `handlers` dictionary was mutated somehow, but it seems unlikely.

Did this suddenly just come on an existing production deploy that's been running for a long time?  Have you changed Meteor versions recently?  Babel plugins?  Anything else that might have mutated `String` somehow?

Re production, yes, unfortunately, we never made it out of preview, although we've all been using the preview versions in production :)  (Note though that `extract` did get a final release, which you should upgrade to, but the fixes were all React parsing related).  Things got a bit hectic with all the Meteor changes over the last two years.  The plan is for in 2016 Q1/H1 to release a new npm based version in line with the new guidelines.

**Comment by Kombustor** [comment]
This package convinces me, but I do not want to use beta software in the final product, which is about to be released in June. Is there an ETA for the out-of-beta release v2? Or is it safe to use in production? @gadicc

**Comment by Maxhodges** [comment]
All software is beta. 
We've been using messageFormat in production around a year-and-a-half.

**Comment by 1u** [comment]
We at [Openki](https://github.com/Openki/Openki) use messageformat since Feb 2014 :) 
I personally consider it quite safe in production. and great in support.

**Comment by gadicc** [comment]
@Kombustor, yeah, I embarrassingly never quite finished this up because of all the changes to Meteor over the last two years (and the consequent impact on my time).  There were a number of things I wanted in a final v2.0.0 release (particularly a single source of up-to-date docs - for you you should know that the various READMEs complement / supercede the docs on the site) but yeah the truth is it's been stable for production use with very few changes over that time period.  I'm actually hoping for an npm-centric v3 release this year sometime.

A big thanks as always to @Maxhodges and @1u for chiming in; our top two production projects / users.  1u is especially kind re support, as I wish I could do better, just have very limited time :(
